-- Larda initial schema. PostgreSQL 15+.
-- Apply once to an empty database, inside a transaction.
-- Authorization, state transitions, rating calculation and EXP payouts belong
-- to the application service layer. This migration defines storage constraints.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL CHECK (btrim(name) <> ''),
    role VARCHAR(20) NOT NULL CHECK (role IN ('business', 'student')),
    company_name VARCHAR(200),
    exp BIGINT NOT NULL DEFAULT 0 CHECK (exp >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(80) NOT NULL UNIQUE
        CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    name VARCHAR(100) NOT NULL CHECK (btrim(name) <> ''),
    kind VARCHAR(20) NOT NULL
        CHECK (kind IN ('specialization', 'technology', 'skill')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE user_tags (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE RESTRICT,
    PRIMARY KEY (user_id, tag_id)
);
CREATE INDEX ix_user_tags_tag ON user_tags (tag_id);

CREATE TABLE teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL CHECK (btrim(name) <> ''),
    description TEXT NOT NULL DEFAULT '',
    interests JSONB NOT NULL DEFAULT '[]'::jsonb
        CHECK (jsonb_typeof(interests) = 'array'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE team_members (
    team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL DEFAULT 'member'
        CHECK (role IN ('captain', 'member')),
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (team_id, user_id)
);
-- At most one captain; the service must ensure every team has one.
CREATE UNIQUE INDEX ux_team_captain ON team_members (team_id)
    WHERE role = 'captain';
CREATE INDEX ix_team_members_user ON team_members (user_id);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    industry VARCHAR(80) NOT NULL DEFAULT '',
    topic VARCHAR(80) NOT NULL DEFAULT '',
    raw_description TEXT NOT NULL CHECK (btrim(raw_description) <> ''),
    title TEXT NOT NULL DEFAULT '',
    context TEXT NOT NULL DEFAULT '',
    need TEXT NOT NULL DEFAULT '',
    target_users TEXT NOT NULL DEFAULT '',
    available_data TEXT NOT NULL DEFAULT '',
    constraints TEXT NOT NULL DEFAULT '',
    expected_result TEXT NOT NULL DEFAULT '',
    success_criteria TEXT NOT NULL DEFAULT '',
    contact TEXT NOT NULL DEFAULT '',
    interaction_format TEXT NOT NULL DEFAULT '',
    feedback_process TEXT NOT NULL DEFAULT '',
    draft_card JSONB CHECK (draft_card IS NULL OR jsonb_typeof(draft_card) = 'object'),
    publication_status VARCHAR(20) NOT NULL DEFAULT 'draft'
        CHECK (publication_status IN ('draft', 'published', 'archived')),
    readiness_score SMALLINT NOT NULL DEFAULT 0 CHECK (readiness_score BETWEEN 0 AND 100),
    score_breakdown JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(score_breakdown) = 'object'),
    confirmed_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    execution_status VARCHAR(20) NOT NULL DEFAULT 'not_started'
        CHECK (execution_status IN ('not_started', 'in_progress', 'completed', 'cancelled')),
    team_exp_reward INTEGER NOT NULL DEFAULT 100 CHECK (team_exp_reward >= 0),
    business_exp_reward INTEGER NOT NULL DEFAULT 50 CHECK (business_exp_reward >= 0),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_tasks_publication CHECK (
        publication_status <> 'published'
        OR (confirmed_at IS NOT NULL AND published_at IS NOT NULL AND btrim(title) <> '')
    ),
    CONSTRAINT ck_tasks_publication_confirmation CHECK (
        published_at IS NULL OR confirmed_at IS NOT NULL
    ),
    CONSTRAINT ck_tasks_unconfirmed_score CHECK (
        confirmed_at IS NOT NULL OR readiness_score = 0
    ),
    CONSTRAINT ck_tasks_completion CHECK (
        (execution_status = 'completed') = (completed_at IS NOT NULL)
    )
);
CREATE INDEX ix_tasks_owner ON tasks (owner_id);
CREATE INDEX ix_tasks_catalog ON tasks (readiness_score DESC, published_at DESC, id DESC)
    WHERE publication_status = 'published';
CREATE INDEX ix_tasks_catalog_topic ON tasks (topic, readiness_score DESC, id DESC)
    WHERE publication_status = 'published';

CREATE TABLE task_tags (
    task_id BIGINT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE RESTRICT,
    PRIMARY KEY (task_id, tag_id)
);
CREATE INDEX ix_task_tags_tag ON task_tags (tag_id);

CREATE TABLE task_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    round_number INTEGER NOT NULL DEFAULT 1 CHECK (round_number > 0),
    position INTEGER NOT NULL CHECK (position > 0),
    field_key VARCHAR(50) NOT NULL CHECK (field_key IN (
        'industry', 'topic', 'title', 'context', 'need', 'target_users',
        'available_data', 'constraints', 'expected_result', 'success_criteria',
        'contact', 'interaction_format', 'feedback_process', 'tag_ids'
    )),
    question TEXT NOT NULL CHECK (btrim(question) <> ''),
    answer TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (task_id, round_number, position)
);

CREATE TABLE proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES tasks(id) ON DELETE RESTRICT,
    team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE RESTRICT,
    submitted_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    solution_idea TEXT NOT NULL CHECK (btrim(solution_idea) <> ''),
    plan TEXT NOT NULL CHECK (btrim(plan) <> ''),
    duration_days INTEGER NOT NULL CHECK (duration_days > 0),
    prototype_url TEXT NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'accepted', 'rejected')),
    decided_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    decided_at TIMESTAMPTZ,
    execution_status VARCHAR(20) NOT NULL DEFAULT 'not_started'
        CHECK (execution_status IN ('not_started', 'in_progress', 'completed', 'cancelled')),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_proposals_decision CHECK (
        (status = 'pending' AND decided_by IS NULL AND decided_at IS NULL)
        OR (status IN ('accepted', 'rejected') AND decided_by IS NOT NULL AND decided_at IS NOT NULL)
    ),
    CONSTRAINT ck_proposals_execution CHECK (
        status = 'accepted' OR execution_status = 'not_started'
    ),
    CONSTRAINT ck_proposals_completion CHECK (
        (execution_status = 'completed') = (completed_at IS NOT NULL)
    )
);
-- Multiple proposals from the same team are allowed.
CREATE INDEX ix_proposals_task_status ON proposals (task_id, status);
CREATE INDEX ix_proposals_team_task ON proposals (team_id, task_id);
CREATE INDEX ix_proposals_submitter ON proposals (submitted_by);
CREATE INDEX ix_proposals_decider ON proposals (decided_by) WHERE decided_by IS NOT NULL;

CREATE TABLE milestones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL REFERENCES proposals(id) ON DELETE RESTRICT,
    position INTEGER NOT NULL CHECK (position > 0),
    title VARCHAR(200) NOT NULL CHECK (btrim(title) <> ''),
    description TEXT NOT NULL DEFAULT '',
    exp_reward INTEGER NOT NULL DEFAULT 100 CHECK (exp_reward >= 0),
    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'submitted', 'completed', 'rejected')),
    result_url TEXT,
    submitted_at TIMESTAMPTZ,
    completed_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (proposal_id, position),
    CONSTRAINT ck_milestones_submission CHECK (
        status = 'pending' OR submitted_at IS NOT NULL
    ),
    CONSTRAINT ck_milestones_completion CHECK (
        (status = 'completed' AND completed_by IS NOT NULL AND completed_at IS NOT NULL)
        OR (status <> 'completed' AND completed_by IS NULL AND completed_at IS NULL)
    )
);
CREATE INDEX ix_milestones_completer ON milestones (completed_by) WHERE completed_by IS NOT NULL;

CREATE TABLE achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE CHECK (code ~ '^[a-z][a-z0-9_]*$'),
    title VARCHAR(150) NOT NULL CHECK (btrim(title) <> ''),
    description TEXT NOT NULL DEFAULT '',
    role_scope VARCHAR(20) NOT NULL CHECK (role_scope IN ('student', 'business', 'all')),
    event_type VARCHAR(40) NOT NULL
        CHECK (event_type IN ('milestone_completed', 'task_completed', 'task_published')),
    target_count INTEGER NOT NULL DEFAULT 1 CHECK (target_count > 0),
    exp_reward INTEGER NOT NULL CHECK (exp_reward > 0),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE user_achievements (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    achievement_id BIGINT NOT NULL REFERENCES achievements(id) ON DELETE RESTRICT,
    unlocked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, achievement_id)
);
CREATE INDEX ix_user_achievements_achievement ON user_achievements (achievement_id);

CREATE TABLE exp_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    -- Zero shares preserve participation when the reward is smaller than the team.
    amount BIGINT NOT NULL CHECK (amount >= 0),
    reason VARCHAR(40) NOT NULL CHECK (reason IN (
        'milestone_completed', 'team_task_completed',
        'business_task_completed', 'achievement_unlocked'
    )),
    milestone_id BIGINT REFERENCES milestones(id) ON DELETE RESTRICT,
    task_id BIGINT REFERENCES tasks(id) ON DELETE RESTRICT,
    team_id BIGINT REFERENCES teams(id) ON DELETE RESTRICT,
    achievement_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_exp_unlocked_achievement FOREIGN KEY (user_id, achievement_id)
        REFERENCES user_achievements(user_id, achievement_id) ON DELETE RESTRICT,
    CONSTRAINT ck_exp_source CHECK (
        (reason = 'milestone_completed'
            AND milestone_id IS NOT NULL AND task_id IS NULL
            AND team_id IS NULL AND achievement_id IS NULL)
        OR (reason = 'team_task_completed'
            AND milestone_id IS NULL AND task_id IS NOT NULL
            AND team_id IS NOT NULL AND achievement_id IS NULL)
        OR (reason = 'business_task_completed'
            AND milestone_id IS NULL AND task_id IS NOT NULL
            AND team_id IS NULL AND achievement_id IS NULL)
        OR (reason = 'achievement_unlocked'
            AND milestone_id IS NULL AND task_id IS NULL
            AND team_id IS NULL AND achievement_id IS NOT NULL AND amount > 0)
    )
);
CREATE UNIQUE INDEX ux_exp_milestone ON exp_transactions (user_id, milestone_id)
    WHERE reason = 'milestone_completed';
CREATE UNIQUE INDEX ux_exp_team_task ON exp_transactions (user_id, task_id, team_id)
    WHERE reason = 'team_task_completed';
CREATE UNIQUE INDEX ux_exp_business_task ON exp_transactions (user_id, task_id)
    WHERE reason = 'business_task_completed';
CREATE UNIQUE INDEX ux_exp_achievement ON exp_transactions (user_id, achievement_id)
    WHERE reason = 'achievement_unlocked';
CREATE INDEX ix_exp_user_history ON exp_transactions (user_id, created_at DESC, id DESC);
CREATE INDEX ix_exp_milestone ON exp_transactions (milestone_id) WHERE milestone_id IS NOT NULL;
CREATE INDEX ix_exp_task ON exp_transactions (task_id) WHERE task_id IS NOT NULL;
CREATE INDEX ix_exp_team ON exp_transactions (team_id) WHERE team_id IS NOT NULL;

-- Initial catalogs, not demo users or project data. Rewards are editable defaults.
INSERT INTO tags (slug, name, kind) VALUES
    ('backend-developer', 'Backend Developer', 'specialization'),
    ('frontend-developer', 'Frontend Developer', 'specialization'),
    ('ml-engineer', 'ML Engineer', 'specialization'),
    ('go', 'Go', 'technology'),
    ('python', 'Python', 'technology'),
    ('react', 'React', 'technology');

INSERT INTO achievements (code, title, description, role_scope, event_type, target_count, exp_reward) VALUES
    ('first_task_completed', 'First task completed',
        'Participate in a completed task.', 'student', 'task_completed', 1, 100),
    ('first_milestone_completed', 'First milestone completed',
        'Participate in a confirmed milestone.', 'student', 'milestone_completed', 1, 50),
    ('first_task_published', 'First task published',
        'Publish your first confirmed task.', 'business', 'task_published', 1, 30),
    ('first_business_task_completed', 'First task delivered',
        'Complete your first task as its business owner.', 'business', 'task_completed', 1, 100);
