-- Keep the original migration intact; all additions are additive.
ALTER TABLE tasks
    ADD COLUMN draft_evaluation JSONB CHECK (draft_evaluation IS NULL OR jsonb_typeof(draft_evaluation) = 'object'),
    ADD COLUMN revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
    ADD COLUMN evaluated_revision BIGINT,
    ADD COLUMN ai_status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (ai_status IN ('pending','running','succeeded','failed')),
    ADD COLUMN ai_error TEXT NOT NULL DEFAULT '';

CREATE TABLE ai_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    revision BIGINT NOT NULL CHECK (revision > 0),
    kind VARCHAR(20) NOT NULL CHECK (kind IN ('questions','generate','evaluate')),
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','running','succeeded','failed','superseded')),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    error TEXT NOT NULL DEFAULT '',
    input JSONB NOT NULL CHECK (jsonb_typeof(input) = 'object'),
    result JSONB,
    lease_token TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (task_id, revision)
);
CREATE INDEX ix_ai_jobs_pending ON ai_jobs (id) WHERE status IN ('pending','running');

ALTER TABLE milestones
    ADD COLUMN proposed_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    ADD COLUMN approved_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    ADD COLUMN approved_at TIMESTAMPTZ,
    ADD CONSTRAINT ck_milestones_approval CHECK ((approved_by IS NULL) = (approved_at IS NULL));
-- Existing milestones predate approval metadata. Preserve them as approved by their task owner.
UPDATE milestones m SET proposed_by = p.submitted_by, approved_by = t.owner_id, approved_at = m.created_at
FROM proposals p JOIN tasks t ON t.id = p.task_id WHERE m.proposal_id = p.id;
ALTER TABLE milestones ALTER COLUMN proposed_by SET NOT NULL;
